# Taps
tap "daipeihust/tap"
# tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazygit"
# tap "oven-sh/bun"
tap "shopify/shopify"

# Formulae
brew "bat"
# brew "bun"
brew "exa"
brew "deno"
brew "dust"
brew "fd"
brew "fzf"
brew "gawk"
brew "gh"
# brew "heroku"
brew "jq"
brew "mas"
brew "nano"
brew "navi"
brew "ncdu"
brew "neovim"
# brew "peco"
brew "procs"
brew "rename"
brew "ripgrep"
brew "tmux"
brew "tree"
# brew "volta"
brew "wget"
brew "daipeihust/tap/im-select"

# Development
brew "ghq"
brew "gibo"
brew "git"
brew "git-delta"
# brew "rust"
brew "skaffold"
brew "sqlite"
brew "jesseduffield/lazygit/lazygit"
brew "shopify/shopify/shopify-cli"
brew "shopify/shopify/themekit"

# Apps
cask "karabiner-elements"
cask "maccy"
cask "stats"
cask "visual-studio-code"
# cask "bitwarden"
# cask "blender"
# cask "brave-browser"
# cask "docker"
# cask "fig"
# cask "google-chrome"
# cask "google-japanese-ime"
# cask "firefox"
# cask "figma"
# cask "iconset"
# cask "iterm2"
# cask "lapce"
# cask "lunar"
# cask "obsidian"
# cask "postman"
# cask "rectangle"
# cask "spotify"
# cask "vscodium"
# cask "warp"

# Mac App Store
# mas "Be Focused - Pomodoro Timer", id: 973134470
# mas "Kindle", id: 405399194
# mas "Line", id: 539883307
# mas "ScreenBrush", id: 1233965871
# mas "Trello", id: 1278508951

# Fonts
cask "font-fira-code-nerd-font"
# cask "font-fira-code"
# cask "font-meslo-lg-nerd-font"
# cask "font-ubuntu-mono-nerd-font"
# cask "font-ubuntu-nerd-font"
# cask "font-victor-mono-nerd-font"
# "operator-mono-lig" # needs to install manually: https://github.com/kiliman/operator-mono-lig 
