volta install node
volta install npm
volta install yarn
volta install pnpm
volta install npm-check-updates
volta install netlify-cli
volta install wrangler
volta install @antfu/ni
volta install better-commits
