# [default_session]
# startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "wezterm config"
path = "~/.config/wezterm"
startup_command = "nvim wezterm.lua"

[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "gitmux config"
path = "~/.config/gitmux"
startup_command = "nvim gitmux.conf"

[[session]]
name = "starship config"
path = "~/.config/starship"
startup_command = "nvim starship.toml"

[[session]]
name = "oh-my-posh config"
path = "~/.config/ohmyposh"
startup_command = "nvim theme.toml"

[[session]]
name = "lazygit config"
path = "~/.config/lazygit"
startup_command = "nvim config.yml"
