return {
  MacroRecording = "",
  ActiveLSP = "", --   
  ActiveTS = "綠",
  BufferClose = "",
  NeovimClose = "",
  DefaultFile = "", --  
  Diagnostic = "裂", -- 裂
  DiagnosticError = "", --  
  DiagnosticHint = "", --   󰰀
  DiagnosticInfo = "", --  
  DiagnosticWarn = "", --  
  Ellipsis = "…",
  FileModified = "",
  FileReadOnly = "", --   
  FolderClosed = "", --   
  FolderEmpty = "", --  
  FolderOpen = "", --  
  Git = "", --  
  GitAdd = "Σ", -- Σ
  GitBranch = "", --  
  GitChange = "", -- 
  GitConflict = "", --  
  GitDelete = "Δ", -- Δ
  GitIgnored = "◌", -- ◌ 
  GitRenamed = "", -- » 
  GitStaged = "", --  
  GitUnstaged = "", -- ✗
  GitUntracked = "", -- ?  
  LSPLoaded = "", --  
  LSPLoading1 = "", --    
  LSPLoading2 = "",
  LSPLoading3 = "",
}
