require("user.plugins-setup") -- should be at the top
require("user.core.options")
require("user.core.keymaps")
require("user.core.colorscheme")
require("user.plugins.comment")
require("user.plugins.nvim-tree")
require("user.plugins.bufferline")
require("user.plugins.lualine")
require("user.plugins.telescope")
require("user.plugins.nvim-cmp")
require("user.plugins.lsp")
require("user.plugins.autopairs")
require("user.plugins.treesitter")
require("user.plugins.gitsigns")
require("user.plugins.toggleterm")
